# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CmdLine@2
  displayName: az cli install
  inputs:
    script: 'curl -sL https://aka.ms/InstallAzureCLIDeb'

- task: CmdLine@2
  displayName: az login
  inputs:
    script: 'az login --az login --service-principal -u 3a6682f8-d121-42ad-9cf6-bed4093a5785 -p 8cF8Q~y323yXVgFjRt3ZhvBz7OEHDJyjCPEvXc5H --tenant 661531e5-7111-438e-9d28-7a630db4c065'

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
  displayName: terraform install

- script: |
    terraform init
  displayName: 'Terraform initialization'

# - script: |
#     terraform plan
#   displayName: 'Terraform plan'

- script: |
    terraform apply 
  displayName: 'Terraform Apply'
