# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CmdLine@2
  displayName: az cli install
  inputs:
    script: 'curl -sL https://aka.ms/InstallAzureCLIDeb'

- task: CmdLine@2
  displayName: az login
  inputs:
    script: 'az login --service-principal --username "2a772d7d-c69a-4450-a7ad-a80e3a41b1e7" --password "7Nw8Q~yhCRNUwfiw5QWb0d4SPWRSjeJwYu1ZFaEf" --tenant "540f532a-c53d-4daf-b68d-3dbb0bf536ce" '

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- script: |
    terraform init
    # terraform plan -out=terraform.tfplan
  displayName: 'Terraform Plan'

# - script: |
#     terraform apply $(Pipeline.Workspace)/terraform.tfplan
#   displayName: 'Terraform Apply'
