# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CmdLine@2
  displayName: az cli install
  inputs:
    script: 'curl -sL https://aka.ms/InstallAzureCLIDeb'

- task: CmdLine@2
  displayName: az login
  inputs:
    script: 'az login --service-principal --username "2b6a2482-3a5f-4d7a-a6ac-35b6ceaad3be" --password ".0L8Q~HYsFOKj~GRH.wm6U9MCDwSwDdREVifwcAp" --tenant "540f532a-c53d-4daf-b68d-3dbb0bf536ce" --subscription "f8231c19-9560-40d1-a65d-a0618d065526"'

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- script: |
    terraform init
    # terraform plan -out=terraform.tfplan
  displayName: 'Terraform Plan'

# - script: |
#     terraform apply $(Pipeline.Workspace)/terraform.tfplan
#   displayName: 'Terraform Apply'
